### ISSUE TITLE
Couldn't build

### ISSUE THREAD

**Issue by ivira** [Krivoblotsky/CleanMyTest#1]
It seems to be the problem with CocoaPods integration. Could you please check.

**Comment by Krivoblotsky** [comment]
Yep. Give me a min.

**Comment by Krivoblotsky** [comment]
Hm, I've just checked and it builds normally on my side. Did you run "pod install" first?
By the way, my config is: OS X 10.10.3 (14D136), XCode Version 6.3.2 (6D2105) CocoaPods 0.37.2.

**Comment by Krivoblotsky** [comment]
I can provide you with ZIP-archive with CocoaPods integrated project included, if you will have no luck with it.

**Comment by Krivoblotsky** [comment]
Here is the zip, just in case: 
https://dl.dropboxusercontent.com/u/11819370/CleanMyTest.zip
Workspace file is: CleanMyTest.xcworkspace
Please tell, if you still experience any issues. 
Thanks!

**Comment by ivira** [comment]
"pod install" did help. Thanks.
